### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by philipbjorge** [andrewconner/slack-hide-typing#1]
This extension helped me workaround a bug in Slack that was spamming typing messages that was getting me kicked from my websocket :+1: !
![pasted image at 2016_05_31 02_56 pm](https://cloud.githubusercontent.com/assets/918891/15692042/027f31f2-2741-11e6-98c7-def1b6532034.png)

**Comment by andrewconner** [comment]
Great, glad it helped you. Thanks!
