### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by wbrewer** [andrewconner/slack-hide-typing#6]
This broke again. Just letting you know.

**Comment by andrewconner** [comment]
Whoops, just noticed this. Thanks for the patience. Fixed in 059c98e2e0b2ff8652199c35e50d8abf254f2ca6. Pushed to Chrome webstore, 1.2.0. Should be available in the next ~hour.

**Comment by wbrewer** [comment]
Thanks man. That feature incorporated into Slack drives me insane.
